### PR TITLE
updated to version 0.2.0

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by corinnekrych** [comment]
+1

**Comment by matzew** [comment]
@edewit was there a JIRA ticket? I am not sure I am able to follow what version 0.2.0 means here, since the desc. is pretty empty.

**Comment by edewit** [comment]
0.2.0 is the latest release of the swift libs

**Comment by matzew** [comment]
Ah, ok - let's make sure the descriptions are covering a bit of details about the actual PR

**Comment by edewit** [comment]
issue [AGCORDOVA-58](https://issues.jboss.org/browse/AGCORDOVA-58)

**Pull request merged**
