### PR TITLE
optional client secret

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by matzew** [comment]
Do we have a JIRA for thios ?

**Comment by edewit** [comment]
it was part of AGCORDOVA-50

**Comment by matzew** [comment]
Ah, cool !

**Comment by matzew** [comment]
@danielpassos @abstractj any comments?

**Comment by danielpassos** [comment]
lgtm

**Comment by abstractj** [comment]
@edewit Landed

**Pull request merged**
