### PR TITLE
update README with Project Info

### PR DESCRIPTION
**Pull request by lfryc**

### CODE REVIEW

**Comment by matzew** [comment]
+1

On Wed, Feb 25, 2015 at 12:06 PM, Lukáš Fryč <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aerogear/aerogear-oauth2-cordova/pull/9
> Commit Summary
>
>    - Update README.md
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/aerogear/aerogear-oauth2-cordova/pull/9/files#diff-0>
>    (30)
>
> Patch Links:
>
>    - https://github.com/aerogear/aerogear-oauth2-cordova/pull/9.patch
>    - https://github.com/aerogear/aerogear-oauth2-cordova/pull/9.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-oauth2-cordova/pull/9>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by edewit** [comment]
:+1:

**Comment by edewit** [comment]
could you rebase @lfryc

**Comment by lfryc** [comment]
@edewit rebased

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
