### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by edewit**
For the update to 2.0.0 some of the packages where renamed. Without these fixes the plugin is not usable for android.

### CODE REVIEW

**Comment by edewit** [comment]
fixes issue [AGCORDOVA-69](https://issues.jboss.org/browse/AGCORDOVA-69)

**Comment by danielpassos** [comment]
:eyes:

**Comment by abstractj** [comment]
@edewit so I think we might need another release, nope?

**Comment by edewit** [comment]
@abstractj definitely it's broken now

**Comment by abstractj** [comment]
@edewit after @danielpassos's review let's release 1.0.3 tomorrow?

**Comment by danielpassos** [comment]
:+1:  Not a big deal, but  `@aar` is not needed anymore because `aar` now is the default type

**Comment by edewit** [comment]
@abstractj yep let's release a new version tomorrow

**Comment by abstractj** [comment]
@edewit landed

**Pull request closed without merging**
